server:
  port: 8080

database:
  gwDbName: gitwize
  gwDbUser: gitwize_user
  gwDbHost: localhost
  gwDbPort: 3306

auth:
  authDisable: 'true'

endpoint:
  frontEnd: 'http://localhost:8080'
  sonarQubeServer: 'http://localhost'

sonarqube:
  scannerPath: '/usr/local/sonarqube/sonar-scanner/bin/sonar-scanner'
  propertiesPath: '/usr/local/sonarqube/sonar-scanner/conf/sonar-scanner.properties'
  baseDirectory: './'
