server:
  port: 8080

database:
  gwDbName: gitwize
  gwDbUser: admin
  gwDbHost: aa1lh3p3ldhesqs.cboppvu0mv3y.ap-southeast-1.rds.amazonaws.com
  gwDbPort: 3306

auth:
  authDisable: 'false'

endpoint:
  frontEnd: 'https://gitwize.net'
