server:
  port: 8080

database:
  gwDbName: gitwize
  gwDbUser: admin
  gwDbHost: dev-gitwize-db.cboppvu0mv3y.ap-southeast-1.rds.amazonaws.com
  gwDbPort: 3306

auth:
  authDisable: 'false'

endpoint:
  frontEnd: 'https://dev.gitwize.net'
  sonarQubeServer: 'https://sonarqube.gitwize.net'

sonarqube:
  scannerPath: '/usr/local/sonarqube/sonar-scanner/bin/sonar-scanner'
  propertiesPath: '/usr/local/sonarqube/sonar-scanner/conf/sonar-scanner.properties'
  baseDirectory: '/tmp/'
