server:
  port: 8080

database:
  gwDbName: gitwize_prod
  gwDbUser: gitwize_prod
  gwDbHost: dev-gitwize-db.cboppvu0mv3y.ap-southeast-1.rds.amazonaws.com
  gwDbPort: 3306

auth:
  authDisable: 'false'

endpoint:
  frontEnd: 'https://gitwize.net'
