server:
  port: 8080

database:
  gwDbName: gitwize
  gwDbUser: gitwize_user
  gwDbHost: localhost
  gwDbPort: 3306

auth:
  authDisable: 'true'

endpoint:
  frontEnd: 'http://localhost:8080'
  sonarQubeServer: 'https://sonarqube.gitwize.net'

sonarqube:
  scannerPath: '/Users/khoa.nguyen/Downloads/sonar-scanner-4.4.0.2170-macosx/bin/sonar-scanner'
  propertiesPath: '/Users/khoa.nguyen/Downloads/sonar-scanner-4.4.0.2170-macosx/conf/sonar-scanner.properties'
