version: "3"
services:
  db:
    image: mysql:8.0
    restart: "no"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_HOST=localhost
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=gitwize_user
      - MYSQL_DATABASE=gitwize
      - MYSQL_PASSWORD=P@ssword123
    ports:
      - "3306:3306"
    command: |
      --character-set-server="utf8"
      --collation-server="utf8_general_ci"
      --sql_mode=""
