name: migration
run-name: migrating workflows from circleci 
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: echo "lint"
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "testgit checkout "